spring:
    application:
        name: estate_search

    threads:
        virtual:
            enabled: true

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${KEYCLOAK_SERVER_URL}/realms/${KEYCLOAK_REALM}
                    jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: oracle.jdbc.OracleDriver
        hikari:
            maximum-pool-size: ${DB_MAX_POOL_SIZE:20} # keep it as small as possible for better performance.
            data-source-properties:
                ApplicationName: ${spring.application.name} # show application's name when using pg_stat_activity
                stringtype: unspecified
                reWriteBatchedInserts: true

    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                "[format_sql]": true
        database-platform: org.hibernate.dialect.OracleDialect

server:
    error:
        whitelabel:
            enabled: false # disable default whitelabel error page.
    shutdown: graceful

keycloak:
    auth-server-url: ${KEYCLOAK_SERVER_URL}
    realm: ${KEYCLOAK_REALM}
    resource: ${KEYCLOAK_CLIENT_ID}
    credentials:
        secret: ${KEYCLOAK_CLIENT_SECRET}
    use-resource-role-mappings: true
    principal-attribute: preferred_username

jwt:
    auth:
        converter:
            resource-id: ${KEYCLOAK_CLIENT_ID}
            principle-attribute: preferred_username
